### ISSUE TITLE
02 - spot component card

### ISSUE THREAD

**Issue by zeldaco** [manoa-spots/manoa-spots.github.io#9]
## Task Instructions

Do all work for this task in a branch called issue-XX

## Description

[Replace this text with a detailed description of what needs to be accomplished for this task.]

## Acceptance Criteria
- [ ] Define the criteria for the task to be considered complete.
- [ ] Complete Component Cards
- [ ] Implement it with the database
- [ ] Include filters, images, name, rating, location, hours, size
- [ ] Include pictures
